### ISSUE TITLE
Private Registry Module resource would be very helpful

### ISSUE THREAD

**Issue by djaboxx** [terraform-providers/terraform-provider-tfe#11]
In order to import modules into TFE Organizations, a registry module resource would be very helpful. Unfortunately, it looks like the go-tfe library doesn't yet implement any functionality for the registry-modules api endpoint. Should I open an issue on that repo as well?

**Comment by nrvale0** [comment]
Have had requests for this from the Field as well.

**Comment by shannonrdunn** [comment]
Module functions are available against the TFE API, any reason to not have this available via the TFE provider?

https://www.terraform.io/docs/cloud/api/modules.html

**Comment by peimanja** [comment]
Any update on this one? this could help us provide a self-service to teams for adding their module in TFE

**Comment by lafentres** [comment]
👋 Hi there! 
Support for registry modules has been added this morning with [the newly released v0.20.0 of the TFE provider](https://github.com/terraform-providers/terraform-provider-tfe/blob/v0.20.0/CHANGELOG.md).

[go-tfe v0.10.0](https://github.com/hashicorp/go-tfe/releases/tag/v0.10.0) also has support for registry modules.
