### ISSUE TITLE
Updating terraform_version attribute on  tfe_workspace fails when it should retry

### ISSUE THREAD

**Issue by scottwinkler** [terraform-providers/terraform-provider-tfe#112]
I am using the TFE provider to  update the terraform_version on about 50 workspaces at the same time. When I `terraform apply` only about 5-12 workspaces will be updated, the rest will fail with a mysterious error message saying the repository doesn't exist or isn't accessible:

```
[1m[31mError: [0m[0m[1mError updating workspace dotnet-services-agentmapping-peg for organization Velocify: Invalid Attribute
Repository doesn’t exist or isn’t accessible[0m
```

This error message doesn't seem to be a permissions issue, however. When I apply again, another 5-12 workspaces will be updated before I get the same error message. It seems to be a problem with performing too many updates at the same time, causing some of the reads to fail. There should be retry logic in the tfe_workspace resource to catch this specific error and retry at least a few times. Currently I have to apply my workspace around 5-10 times before the deployment succeeds.

**Comment by OnionTing** [comment]
I have opened the support ticket for you. let's follow up there. thank you Scott.

**Comment by koikonom** [comment]
Since this issue was worked out with support, I will be closing it. Thanks for taking the time to report it!

**Comment by wchrisjohnson** [comment]
What was the resolution of this issue? I am experiencing the same issue now.
