### ISSUE TITLE
Support Sentinel Policies Parameter

### ISSUE THREAD

**Issue by mechastorm** [terraform-providers/terraform-provider-tfe#118]
It would be great if we can support the creation of parameters for a Sentinel Policy via the TFE provider. 

This seems to be now support in Terraform Enterprise On-Prem (though I am not sure if Terraform Cloud has this yet).

Currently, we need to do this through the UI but it would be great if we can define this in code so that it can go through the normal code review and TF pipeline.

**Comment by dylanegan** [comment]
@mechastorm thanks for the request. The support for this was recently added to `go-tfe` through https://github.com/hashicorp/go-tfe/pull/97. Support in the provider will be made available in the near future. We are tracking it internally and will add this GitHub issue as a reference.

**Comment by glenngillen** [comment]
@mechastorm just a heads up that the pull request to support this has been added in #119

**Comment by cam-stitt** [comment]
Apologies, the pull request that will add support for parameters has changed to #123 .

**Comment by caseylang** [comment]
Closing with the merger of #123
