### ISSUE TITLE
Plan workspace working directory does not show changes

### ISSUE THREAD

**Issue by etopeter** [terraform-providers/terraform-provider-tfe#136]
I'm trying to remove tfe_workspace working_directory attribute and essentially point it to root directory of repository (default action). However removal of this attribute does not show any changes in plan. When I set working_directory = "" , that is also not showing any changes. The only way to work around this is to put space as value for working_directory.

BEFORE:
```
resource "tfe_workspace" "test_workspace" {
  name = "test"
  organization = "test"
  working_directory = "some_path_in_repository"
...
}
```
CHANEG TAKE 1:
```
resource "tfe_workspace" "test_workspace" {
  name = "test"
  organization = "test"
  working_directory = ""
...
}
```
CHANGE TAKE 2:
```
resource "tfe_workspace" "test_workspace" {
  name = "test"
  organization = "test"
  // removed working_directory
...
}
```
Result:
Both code changes resulted in no changes to plan.

Expected result:
Terraform plan should show changes that working directory is about to be set to nothing and apply default path root of repository.

Provider version tested: v0.13.0, v0.14.0

**Comment by nicsnet** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-tfe/pull/137
