### ISSUE TITLE
Policy vcs_repo can't be updated

### ISSUE THREAD

**Issue by etopeter** [terraform-providers/terraform-provider-tfe#140]
tfe_policy_set can create vcs_repo configuration but it's not able to make changes. Plan shows changes to be made and apply says it changed resources but running plan again shows changes were not applied.

How to reproduce:
First create policy set:
```
resource "tfe_policy_set" "foo" {
  name = "foo"
  vcs_repo {
    identifier = "github-repo"
    oauth_token_id = "token-id"
  }
}
```

Next update let's add ingress_submodules attribute:
```
resource "tfe_policy_set" "foo" {
  name = "foo"
  vcs_repo {
    identifier = "github-repo"
    ingress_submodules = true
    oauth_token_id = "token-id"
  }
}
```
Possible solution:
I don't see anywhere in update section of the code to check vcs_repo changes. There is for Create and Read but for Update is missing. 
https://github.com/terraform-providers/terraform-provider-tfe/blob/master/tfe/resource_tfe_policy_set.go#L227

**Comment by etopeter** [comment]
After some investigation it turns out go-tfe is not supporting updating VCSRepo nor PoliciesPath which is not part of my issue but those properties go together. I created Issue for that modul [go-tfe Issue 105](https://github.com/hashicorp/go-tfe/issues/105)

**Comment by hcrhall** [comment]
@etopeter just to let you know that we have resolved this issue in the following pull request https://github.com/terraform-providers/terraform-provider-tfe/pull/185

The v0.19.0 release includes the new functionality so closing out this issue. Thanks for bringing it to our attention.
