### ISSUE TITLE
tfe_workspace is unable to set github-app-installation-id

### ISSUE THREAD

**Issue by achew22** [terraform-providers/terraform-provider-tfe#147]
Through some API poking and documentation reading it looks like there is a field that is unsettable through the terraform API exposed.

When I `curl` to `https://app.terraform.io/api/v2/organizations/:organization/workspaces` for my preexisting workspace that was configured using the web UI, I can see that the `vcs-repo` is configured to have a `github-app-installation-id` instead of an `oauth_token_id`. When I go to the docs on [`tfe_workspace`](https://www.terraform.io/docs/providers/tfe/r/workspace.html) it doesn't appear that a parameter by that name exists. When I set it I get something like :

```
Error: Unsupported argument

  on terraform.tf line 24, in resource "tfe_workspace" "depot":
  24:     github_app_installation_id = "<SNIP>"

An argument named "github_app_installation_id" is not expected here.
```

Is there another option that I can use to set this? I tried it with all the permutations of `-` and `_`. Is it not possible to use terraform to configure terraform?

Thank you so much!

**Comment by caseylang** [comment]
The GitHub App VCS connection is not available in TFE at the moment. We are investigating the feasibility of its addition. Once it is available, support for its setting will be adding to the provider.

**Comment by achew22** [comment]
Do you think we could use this issue to track documenting that this isn't supported?

**Comment by preston-hf** [comment]
It's unclear why this is closed.

**Comment by valar999** [comment]
When a workspace is created using UI, `github-app-installation-id` is set to id from https://app.terraform.io/api/v2/github-app-installations endpoint. Unfortunately, this endpoint is not available via bearer token. I think this blocks implementation of the feature.

**Comment by kallangerard** [comment]
I think this issue should be reopened. It's still an issue even if there's not a clear path forward at the moment. And I don't think it's a permanent blocker that the endpoint isn't available from a non-user token.

**Comment by c4milo** [comment]
Would it be possible to re-open? this is still very much still an issue it seems.

**Comment by condescendent** [comment]
I got the same issue when trying to connect a github repo from a new workspace. any suggestions ?
