### ISSUE TITLE
TF Cloud (Hosted TFE) Organization Membership

### ISSUE THREAD

**Issue by claywd-bestow** [terraform-providers/terraform-provider-tfe#152]
The TFE provider does not include a resource to call the api and invite a user to the org. I'd like to contribute that logic and resource so we can invite users and reference their account ids from other resources within the 

API reference: https://www.terraform.io/docs/cloud/api/organization-memberships.html
TFE Provider reference: https://www.terraform.io/docs/providers/tfe/index.html

Suggested resource  to be contributed:
```hcl
resource "tfe_organization_user" "" {
    id= "user-V3R563qtJNcExAkN"
    name= null #Set in provider after pulling by id
    email= null #Set in provider after pulling by id
    teams = [ #Provided value used to assign teams when adding to the org. 
            "sample_dev",
     ]
}
```

Only thing I am unsure about is any token actually has access to get the user id of any user. It looks like the only way of doing that is via the org/teams api, which is impossible if a user isn't in an org yet.

**Comment by leetrout** [comment]
Hey @claywd-bestow 👋 You should be able to accomplish this with these new resources:

- [Organization Membership](https://www.terraform.io/docs/providers/tfe/r/organization_membership.html) to invite users to your org via email address.
- [Team Organization Member](https://www.terraform.io/docs/providers/tfe/r/team_organization_member.html) to assign the organization membership to a team. This works with memberships that have yet to accept their invitation as well.

**Comment by lafentres** [comment]
Closing as this was orginally added in 0.16.0

Today's release of 0.20.0 also added a data source and the ability to import organization memberships as well as a computed attribute for user_id.
