### ISSUE TITLE
The documentation for importing `tfe_workspace` should suggest workspace id

### ISSUE THREAD

**Issue by achew22** [terraform-providers/terraform-provider-tfe#153]
The documentation for importing `tfe_workspace` should suggest workspace id as the import ID but instead suggests `my-org-name/my-workspace-name` as the import idea.

When run with `my-org-name/my-workspace-name` I get the following error:

```
Error: Error reading configuration of workspace my-org-name/my-workspace-name: invalid value for workspace ID
```

When using the workspace ID, which I got from https://app.terraform.io/app/my-org-name/workspaces/my-workspace-name/settings/general

**Comment by chrisarcand** [comment]
Thanks for reporting! Indeed, that does need some adjustment.
