### ISSUE TITLE
Repository doesn’t exist or isn’t accessible

### ISSUE THREAD

**Issue by andres-de-castro** [terraform-providers/terraform-provider-tfe#158]
We are using a for_each to create workspaces on tf cloud, we have 40 different workspaces (this is number 40) and we are getting this error when trying to create them.

Terraform v0.12.16
Initializing plugins and modules...
2020/04/07 14:56:46 [DEBUG] Using modified User-Agent: Terraform/0.12.16 TFC/4b8367e79b
tfe_workspace.this_workspace["workspace_name"]: Creating...

Error: Error creating workspace <this_workspace> for organization <org>: Invalid Attribute

Repository doesn't exist or isn't accessible

  on main.tf line 36, in resource "tfe_workspace" "this_workspace":
  36: resource "tfe_workspace" "this_workspace" {

**Comment by andres-de-castro** [comment]
Turns out the VCS connection was disabled, can we get a better error when this occurs?

**Comment by koikonom** [comment]
HI @andres-de-castro. Thanks for taking the time to report this issue.

Unfortunately the provider just passes on the error that we get from the TFC API. You can, if you want, reach out to TFC's support team and discuss this further.

**Comment by ame-everycity** [comment]
reconnect your version control.
