### ISSUE TITLE
tfe_run_trigger creation fails: resource not found.

### ISSUE THREAD

**Issue by jgreat** [terraform-providers/terraform-provider-tfe#161]
```
Terraform v0.12.24
+ provider.tfe v0.16.0
```

I'm trying to create a run trigger on one of the Terraform Cloud workspaces I'm managing. The creation of the run trigger fails with a message like: 

```
Error creating run trigger on workspace ws-LLrtFXWqQkV3D4ic with sourceable ws-fEWnfbPDppptF47M: resource not found
```

I have checked via API and Web Console that these workspaces do exist and and the IDs are correct.

I can manually create the run trigger and import the resource.  At that point Terraform recognizes the resource and additional plans don't try to create/recreate the trigger.

Here's an example of what I'm trying to do.

```
terraform {
  backend "remote" {
    organization = "myorg"
    workspaces {
      name = "tf-cloud"
    }
  }
  required_version = ">= 0.12.24"
}

locals {
  tf_org         = "myorg"
  oauth_token_id = "ot-aaaaaaaaaaaaaaa"
}

provider "tfe" {
  version = "~> 0.16.0"
}

data "tfe_workspace" "tf-cloud" {
  name         = "tf-cloud"
  organization = local.tf_org
}

resource "tfe_workspace" "vpn" {
  name                  = "vpn"
  organization          = local.tf_org
  auto_apply            = true
  file_triggers_enabled = false
  queue_all_runs        = false
  terraform_version     = "0.12.24"

  vcs_repo {
    identifier     = "myorg/terraform/vpn"
    oauth_token_id = local.oauth_token_id
  }
}

resource "tfe_run_trigger" vpn-tf-cloud" {
  workspace_external_id = tfe_workspace.vpn.id
  sourceable_id         = data.tfe_workspace.tf-cloud.id
}
```

`terraform plan` works as advertised. 

```
➜ tf plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

Waiting for the plan to start...

Terraform v0.12.24
Configuring remote state backend...
Initializing Terraform configuration...
2020/04/16 15:56:52 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/5fce96c1ec
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.tfe_workspace.tf-cloud: Refreshing state...
...
tfe_workspace.vpn: Refreshing state... [id=ws-LLrtFXWqQkV3D4ic]
...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tfe_run_trigger.vpn-tf-cloud will be created
  + resource "tfe_run_trigger" "vpn-tf-cloud" {
      + id                    = (known after apply)
      + sourceable_id         = "ws-fEWnfbPDppptF47M"
      + workspace_external_id = "ws-LLrtFXWqQkV3D4ic"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

But apply in Terraform Cloud fails:

```
Terraform v0.12.24
Initializing plugins and modules...
2020/04/16 18:10:57 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/875820a8e6
tfe_run_trigger.vpn-tf-cloud: Creating...

Error: Error creating run trigger on workspace ws-LLrtFXWqQkV3D4ic with sourceable ws-fEWnfbPDppptF47M: resource not found

  on vpn.tf line 15, in resource "tfe_run_trigger" "vpn-tf-cloud":
  15: resource "tfe_run_trigger" "vpn-tf-cloud" 
```

Side note: The documentation for `tfe_run_trigger` needs to be updated to change references for `external_id` to just `id`

**Comment by rlaveycal** [comment]
The creation code is actually in the `go-tfe` repo https://github.com/hashicorp/go-tfe/blob/7a20a8c2dbd17a5731c35b452b1ac756ad124157/run_trigger.go#L117 but it looks like the error is coming from TF-Cloud itself not the client.

**Comment by caseylang** [comment]
Hey @jgreat,

I was unable to recreate your issue using a configuration matching your's. I suspect you're running into a permission issue here with the TFC token you're using to execute this plan/apply. That `resource not found` error you're hitting aligns with a permission issue as well. 

Could you confirm that the token you're using here is a user token and that the token as a) admin access to the `vpn` workspace and b) at least read access to the `tf-cloud` workspace. 

(Your example is also missing a `"` in the resource declaration for `resource "tfe_run_trigger" vpn-tf-cloud"` but I'm assuming that's a copy/paste error, since Terraform would complain in a totally different way if that was in the actual config 😄 )

More info on permissions for Run Triggers can be found [here](https://www.terraform.io/docs/cloud/workspaces/run-triggers.html#creating-a-run-trigger).

**Comment by jgreat** [comment]
@caseylang @rlaveycal thanks for looking into this.

Yes the missing quote was just a copy-pasta typo. The "real" code has some identifiers that I wanted to remove.

Well I guess its a permission issue, but I'd call this a bug on the TF Cloud side. 

The token I'm using is an Organization Token.  Both of the workspaces are a part of the same organization.  I created the workspaces and can modify other resources (add/remove variables, change settings...) that are part of those workspaces with that token.  It would be very silly if I couldn't use this token to create a Run Trigger, but that seems to be the case. If I use my personal user token, the Run Trigger creation works.

I'll pursue this with Terraform.  Thanks again for the help.

**Comment by rlaveycal** [comment]
I've also raised a support issue with Hashicorp.

>I’m using an Org API Token. If I use an Owners team token then it works.
>I would classify this as a bug as to quote https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html#organization-service-accounts  “Organization API tokens are designed for creating and configuring workspaces and teams”
The Docs for the API (https://www.terraform.io/docs/cloud/api/run-triggers.html) do state that admin permission is required. However the Org tokens docs also state that:
Any API endpoints that can't be used with an organization API token include a note like the following:
Note: This endpoint cannot be accessed with organization tokens. You must access it with a user token or team token.
And the Run-Triggers API does NOT have this disclaimer.
