### ISSUE TITLE
tfe_organization_membership Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by conzy** [terraform-providers/terraform-provider-tfe#165]
Hi Folks. Having an issue with the new `tfe_organization_membership` resource using version `v0.16.1` of the provider. Let me know if you need any additional info

```hcl
provider "tfe" {
  hostname = "app.terraform.io"
  token    = var.token
  version  = "~> 0.16.1"
}

resource "tfe_organization_membership" "test" {
  organization = var.organization
  email        = "some_email@gmail.com"
}
```

```
Terraform v0.12.24
Initializing plugins and modules...
2020/05/01 17:56:05 [DEBUG] Using modified User-Agent: Terraform/0.12.24 TFC/a8a62a8589
tfe_organization_membership.test: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to tfe_organization_membership.test, provider
"registry.terraform.io/-/tfe" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by leetrout** [comment]
Hey @conzy 👋 

I've tried a few times in my test environment and just now from my personal laptop with my personal TFC account and I'm not able to recreate this issue with a fresh run.

It looks like you're using TFC with the remote backend- could you share the run ID or the org and workspace names? You can email me at lee.trout@hashicorp.com.

Have you tried re-applying? Is this happening every time you apply?

**Comment by conzy** [comment]
Thanks Lee, I emailed you the run ID.

Some additional context:

Sending the invitation succeeds. But the state is never updated. Trying to apply again predictably results in the following error:

```
Error: Error creating membership user@gmail.com for organization ORG: invalid attribute

User is already an organization member
```

I am using an Organization Token and this is a Terraform Cloud Workspace

**Comment by conzy** [comment]
Just following up on this.

If I use my user token ( I am the organisation owner) this works without issue

If I use the organisation token I get the error above (even though the invite is successfully sent)

**Comment by conzy** [comment]
The plot thickens.. The above is not necessarily true. I think there is also a bit of a documentation issue here.

I noticed when trying to create a user in the Terraform Cloud UI the user must be invited AND assigned to an initial team. The documentation for the [organization_membership](https://www.terraform.io/docs/providers/tfe/r/organization_membership.html) does not mention this.

In order for this to work. I must:

- Use my user token
- Create `tfe_organization_membership` and `tfe_team_organization_member` resources

Example Code that works with user token:

```hcl
data "tfe_team" "test" {
  name         = "engineering"
  organization = "my_org"
}

resource "tfe_organization_membership" "test" {
  organization = "my_org"
  email        = "email@gmail.com"
}

resource "tfe_team_organization_member" "test" {
  team_id                    = data.tfe_team.test.id
  organization_membership_id = tfe_organization_membership.test.id
}
```

Is there any reason this would not work with an org token? The docs [here](https://www.terraform.io/docs/cloud/api/organization-memberships.html#invite-a-user-to-an-organization) indicate this should work
> Note: Organization membership management is restricted to members of the owners team, the owners team API token, and the organization API token.


What is also confusing is that this [API documentation](https://www.terraform.io/docs/cloud/api/team-members.html#organization-membership) seems to contradict my findings

> Note: To add users to a team, they must first be invited to join the organization by email, and accept the invitation. This ensures that you don't accidentally add the wrong person by mistyping a username. See the Organization Memberships API documentation for more information.

I also upgraded from the trial to the team plan to ensure this issue was not related to the account being a trial etc.

For the most part I have really enjoyed using Terraform Cloud so far. But some issues with the distinction between the privilege level of tokens has been very frustrating  e.g an org token being able to create a workspace but needing a team token to enable notifications on that workspace

**Comment by leetrout** [comment]
Excellent info, thanks for the write ups! 

> If I use the organisation token I get the error above (even though the invite is successfully sent)

When I use an org token the invite is sent successfully and I get a permission error as compared to the "inconsistent result after apply" you got:

```
tfe_organization_membership.test: Creating...

Error: Error reading configuration of membership ou-xBBgEupQxDVFw6JR: forbidden

  on main.tf line 1, in resource "tfe_organization_membership" "test":
   1: resource "tfe_organization_membership" "test" {
```

You are right, it should be working with an org token since we are reading the org user we just created using that very token. Based on the permissions matrix in the documentation you linked this is a bug.

We added these new resources to this provider (`tfe_organization_membership`, `tfe_team_organization_member`) using the organization memberships API (documented) and the ability to tie a team membership to the organization user (appears to be undocumented). 

> I noticed when trying to create a user in the Terraform Cloud UI the user must be invited AND assigned to an initial team.

Yes! We do those steps together so when the user accepts the invitation they don't hit a 403 forbidden page because they have no access because they are not on a team. The system doesn't require that both resources be created together but it is likely you will always want to create both. Again, based on the documentation you should be able to manage both of these resources with an organization token.

I'll do some more digging!

**Comment by leetrout** [comment]
@conzy we identified the permissions differences with org tokens and I have a PR out for that. I'll post an update on here next week!

**Comment by leetrout** [comment]
@conzy I have a few changes to make on my PR which I plan to hit tonight. Sorry for the delay.

**Comment by conzy** [comment]
No problem Lee. This isn't blocking me as I just invited users the old fashioned way and am handling team membership with terraform

**Comment by leetrout** [comment]
@conzy could you try again? I've deployed and tested org membership with an org token and it is working as expected now.

If it works would you mind closing this issue? Thanks again for all the help!

I am unassignning me 👋

**Comment by caseylang** [comment]
Closing with updates to TFC
