### ISSUE TITLE
Key cannot be updated for a sensitive variable

### ISSUE THREAD

**Issue by tedivm** [terraform-providers/terraform-provider-tfe#170]
If you try to update the keyname of a sensitive variable you get the following error-

```
Error: Error updating variable var-eT6jQYPvBz5mzxCH: invalid attribute

Key cannot be updated for a sensitive variable
```

I think replacing the variable would make more sense in this context.

**Comment by bendrucker** [comment]
Good news, this will be fixed by https://github.com/terraform-providers/terraform-provider-tfe/pull/175! Coincidentally ran into this around the same time. 

For now, the best workaround is to `terraform taint` the appropriate `tfe_variable`.
