### ISSUE TITLE
[Feature Request] Add tfe_module resource

### ISSUE THREAD

**Issue by mkjmdski** [terraform-providers/terraform-provider-tfe#198]
Hi :).

Recently we have reorganized our terraform enteprise code both on side of git instance and the terraform itself. We started to use multiple organisation and we have noticed that each of them requires adding modules published on git separetly. The propsed feature request includes defining module as a code. The following API could look like this

```HCL
resource "tfe_oauth_client" "test" {
  organization     = "my-org-name"
  api_url          = "https://ado.example.com"
  http_url         = "https://ado.example.com"
  oauth_token      = "my-vcs-provider-token"
  private_key      = "-----BEGIN RSA PRIVATE KEY-----\ncontent\n-----END RSA PRIVATE KEY-----"
  service_provider = "ado_server"
}

resource "tfe_module" "example_module" {
   vcs_id = tfe_oauth_client.test.id
   oauth_token_id = tfe_oauth_client.test.oauth_token_id
   repository = "terraform/modules/google/terraform-google-example-module"
}
```

**Comment by lafentres** [comment]
Hi there! This was added in [v0.20.0](https://github.com/terraform-providers/terraform-provider-tfe/blob/master/CHANGELOG.md#0200-july-17-2020). You can see the [PR here](https://github.com/terraform-providers/terraform-provider-tfe/pull/191) and the [documentation here](https://www.terraform.io/docs/providers/tfe/r/registry_module.html).

The example you gave above would look something like this:
```terraform
resource "tfe_oauth_client" "test" {
  organization     = "my-org-name"
  api_url          = "https://ado.example.com"
  http_url         = "https://ado.example.com"
  oauth_token      = "my-vcs-provider-token"
  private_key      = "-----BEGIN RSA PRIVATE KEY-----\ncontent\n-----END RSA PRIVATE KEY-----"
  service_provider = "ado_server"
}

resource "tfe_registry_module" "example_module" {
  vcs_repo {
    display_identifier = "my-org-name/terraform-provider-name"
    identifier         = "my-org-name/terraform-provider-name"
    oauth_token_id     = tfe_oauth_client.test.oauth_token_id
  }
}
```
