### ISSUE TITLE
Does not work with Terraform 0.13 on TFC

### ISSUE THREAD

**Issue by ktham** [terraform-providers/terraform-provider-tfe#209]
## Error msg

<img width="673" alt="Screen Shot 2020-08-24 at 9 46 56 AM" src="https://user-images.githubusercontent.com/882701/91072734-c945e680-e5ee-11ea-90e5-3f509cbabfb3.png">

## Provider version
```
terraform {
  required_version = "0.13.0"

  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.21.0"
    }
  }
}

provider "tfe" {
  token = var.tfe_token
}
```

**Comment by koikonom** [comment]
Hi @ktham!

I tried reproducing the issue you reported but I was not able to. I created a new workspace and linked it to a test github repo that contained just the following code:

```hcl
terraform {
  required_version = "0.13.0"

  required_providers {
    tfe = {
      source  = "hashicorp/tfe"
      version = "0.21.0"
    }
  }
}

provider "tfe" {}

resource "tfe_organization" "test" {
  name  = "a-random-org-name"
  email = "admin@company.com"
}

```

Are you still experiencing the same issue?

**Comment by ktham** [comment]
Hi @koikonom ! Thanks for follow up. I experience this when trying to upgrade from 0.12.29 to 0.13.0. So first try doing the former, create a few resources, then do the upgrade and you'll run into this issue

**Comment by koikonom** [comment]
Hi @ktham, I tried that as well (set version to 0.12.29, plan, apply, set version to 0.13, plan, apply) and I'm still not able to hit the same error.

Can you please set an environment variable TF_LOG with the value of 1, reproduce the issue and send us the log in a gist? (Be careful not to include any tokens or other sensitive information)

**Comment by sethbacon** [comment]
I'm also having same issue. I will also try to get a log.

**Comment by sethbacon** [comment]
Plan
https://gist.github.com/sethbacon/e80ff3430a03d321ae689c66fc3e04c2

Truncated large sections of this due to sheer size...Tried to leave the interesting bits...

Apply
https://gist.github.com/sethbacon/f0f0322c78d5b03d97f66696f265de12

**Comment by koikonom** [comment]
Excellent, thank you very much for the logs. I will look into it and get back to you!

**Comment by sethbacon** [comment]
BTW, I can confirm a new workspace using the TFE provider with no existing state works fine within my TF Cloud organization.

**Comment by koikonom** [comment]
This is also reported in https://github.com/hashicorp/terraform/issues/26075 .

As a (one-off) workaround please use the `terraform state replace-provider` command, look at https://github.com/hashicorp/terraform/issues/26075#issuecomment-684901514 for an example.

**Comment by sethbacon** [comment]
That worked to clear the issue for me.

**Comment by ktham** [comment]
That worked for me also. Thanks guys! I'll close this issue
