### ISSUE TITLE
Associate ssh key to workspace

### ISSUE THREAD

**Issue by robinbowes** [terraform-providers/terraform-provider-tfe#37]
I don't see a way to associate a (pre-existing) TFE ssh key with a TFE workspace - is this not-yet-implemented, or am I missing something?

**Comment by svanharmelen** [comment]
@robinbowes the resource `tfe_ssh_key` lets you upload an existing private key to TFE: https://www.terraform.io/docs/providers/tfe/r/ssh_key.html#argument-reference

Is that what you were looking for?

**Comment by robinbowes** [comment]
@svanharmelen No, I want to associate a key with a workspace, possibly having uploaded it with the `tfe_ssh_key` resource.

See "Assign an SSH key to a workspace" on this page: https://www.terraform.io/docs/enterprise/api/workspaces.html

I've worked around the issue for now by writing python code that uses the `PATCH /workspaces/:workspace_id/relationships/ssh-key` API endpoint.

I would probably also need a tfe provider data source to lookup an existing ssh key by name to get the ID to use in any `tfe_workspace_ssh_key` resource.

**Comment by svanharmelen** [comment]
Ah, I see... I just created a PR (#38) to add a `ssh_key_id` field to the `tfe_workspace` resource. That should give you a way to assign an SSH key to a workspace.

And I guess adding a data source to find already existing SSH keys would indeed be helpful here. We are planning to add several data sources in an upcoming release, so I just added this one to the list.

**Comment by robinbowes** [comment]
Excellent - I shall look forward to using this (and the data source) when the provider is released.

TBH, I can probably test a pre-release if I can figure out how to build the provider.

**Comment by svanharmelen** [comment]
This issue was closed by PR #38
