### ISSUE TITLE
Please add ‘notification_configuration’(?) resource

### ISSUE THREAD

**Issue by hagurganus** [terraform-providers/terraform-provider-tfe#68]
With the release of the notifications feature for TFE on 3/1, and the corresponding [Notification Configurations](https://www.terraform.io/docs/enterprise/api/notification-configurations.htm) API, it’d be nice to see that added as a resource in the TFE provider.

I may endeavor to do this myself, but I thought I’d add a ‘feature request’ here in the Issues tracker in case anyone else is considering doing the same work.

**Comment by svanharmelen** [comment]
Thanks for reaching out @hagurganus! We are working on adding support for notifications, so it will be added to the provider in an upcoming release.

**Comment by v6** [comment]
For now, would you recommend to use a null resource and comment with a link to this GH issue?

**Comment by enriquerecarte** [comment]
Hi @svanharmelen is there an estimate on when the next release could be? Would be really good to manage the notifications in terraform.

**Comment by svanharmelen** [comment]
I think we should divert that question to @caseylang as he is the one currently working on this. So @caseylang any estimate for when this will be added to the provider? Thanks!

**Comment by caseylang** [comment]
Hi there! This is scheduled to be added in July. Apologies for the delay!

**Comment by hagurganus** [comment]
Awesome, thanks!
