### ISSUE TITLE
Add variables to tfe_team resource for managing organization

### ISSUE THREAD

**Issue by sahilarora535** [terraform-providers/terraform-provider-tfe#69]
TFE introduced concept of teams which have special access in an organizations, which can:
1. Manage policies
2. Manage workspaces
3. Manage VCS connection

Add these features to TFE provider tfe_team resource

See: https://www.terraform.io/docs/enterprise/api/teams.html

**Comment by svanharmelen** [comment]
Thanks for opening this issue @sahilarora535! We didn't yet add these new options as the API around this will be refactored shortly.

So we decided to wait with adding support for this until that refactoring is done, to prevent doing the implementation twice (as there is a change the API changes will be backwards incompatible).

I will leave this ticket open and will follow up when the refactoring is done and support can be added to the provider.

**Comment by sahilarora535** [comment]
@svanharmelen any updates on this? It has been long since this ticket was opened.

**Comment by svanharmelen** [comment]
Unfortunately I don't have insights on that part anymore. Hopefully someone else answer that question...

**Comment by sean-nixon** [comment]
Just discovered this issue one year after it was created. Are there plans to implement this anytime soon? I'd be happy to submit a PR leveraging the existing API if that makes sense at this point. Who would have insight into that? It looks like @beekus and @lafentres have been the most active maintainers lately. Would either of you be able to clarify future plans on this issue?

**Comment by ausfestivus** [comment]
Keen for this as well.

Im elbow deep in devising a TFE RBAC model for my customer and this missing API functionality is a real buzzkill on our automation of onboarding new tenants/organization to the TFE  instance.
