### ISSUE TITLE
Please add resource for managing custom Terraform versions

### ISSUE THREAD

**Issue by blalor** [terraform-providers/terraform-provider-tfe#70]
Something around [this api endpoint](https://www.terraform.io/docs/enterprise/api/admin/terraform-versions.html), to allow adding new/custom versions of Terraform.

**Comment by svanharmelen** [comment]
Thanks for the request @blalor! Currently the admin API's are out of scope (both in this provider and the Go SDK), but I can see how this could be helpful/useful.

So I'll leave this issue open and will think, and have some discussions, about the best way to add support for admin endpoints to the SDK and provider.

**Comment by blalor** [comment]
Understood.  Thank you!

**Comment by svanharmelen** [comment]
Coming back on this one sooner than expected, but it seems this is not an API and resource that we would like to support. The main reason being that you cannot do lifecycle management on a Terraform version which makes it a bad fit for a Terraform resource. So closing this issue as `wontfix`.

**Comment by hairmare** [comment]
I'm not quite sure I get why this cannot be lifecycle managed... Wouldn't I be able to use output from such a resource as an argument to `terraform_version` on a `tfe_workspace` resource? 
Also, the API endpoint is like a classical RESTful endpoint supporting all the verbs needed for resource lifecycle management.

My use-case is that I just built a "version" using the `terraform-bundle` command on a CI environment and I would now like to deploy that into a PTFE instance without manual intervention. I already have all the bits and pieces I would need to pass into the API linked by @blalor 

@svanharmelen I'm ok if the API is out of scope but can't seem to follow along with regards to why it cannot be life-cycle managed.

**Comment by svanharmelen** [comment]
@hairmare I can see how that comment may not be accurate anymore. The API indeed offers all CRUD endpoints needed to be able to manage versions. 

But this provider does not support any of the admin endpoints, so managing Terraform versions is indeed out of scope.
