### ISSUE TITLE
Cannot create variable with empty value using `tfe_variable` resource

### ISSUE THREAD

**Issue by sudomateo** [terraform-providers/terraform-provider-tfe#71]
Terraform throws the following error when creating a variable using the `tfe_resource` resource with an empty `value` attribute.

```
Error: Error applying plan:

1 error(s) occurred:

* tfe_variable.use: 1 error(s) occurred:

* tfe_variable.use: Error creating env variable test_var: value is required
```

This error is thrown whether the `category` attribute is set to `env` or `terraform`. The Terraform Enterprise web interface _does_ allow the creation of empty value variables.

The code I used to reproduce this is below.

```
provider "tfe" {
  token = "${var.tfe_token}"
}

variable "tfe_token" {
  type = "string"
}

variable "tfe_organization" {
  type    = "string"
  default = "example-org"
}

variable "tfe_workspace" {
  type    = "string"
  default = "example-workspace"
}

resource "tfe_workspace" "example" {
  name         = "${var.tfe_workspace}"
  organization = "${var.tfe_organization}"
}

resource "tfe_variable" "example" {
  key          = "test_var"
  value        = ""
  category     = "env"
  workspace_id = "${tfe_workspace.example.id}"
}
```
Maybe the `value` attribute in the `tfe_variable` resource should be marked optional.
* https://github.com/terraform-providers/terraform-provider-tfe/blob/master/tfe/resource_tfe_variable.go#L31

If so then the `go-tfe` might need to stop checking for a valid value.
* https://github.com/hashicorp/go-tfe/blob/master/variable.go#L132-L134

Also noting that you can create a variable within an empty value via the API even though the [API documentation](https://www.terraform.io/docs/enterprise/api/variables.html) lists the `data.attributes.value` attribute as required.

**Comment by svanharmelen** [comment]
Thanks for opening this issue @sudomateo. I wonder if this is a bug in the API, as I cannot think of a good use case for creating an empty variable. I'll discuss this internally, but if you can share your use case in the meantime that will be very useful. Thanks!

**Comment by sudomateo** [comment]
Looks like the following pull requests are in progress. Once they are merged and released we can most likely update this provider to make the `value` attribute optional and default to `""`.
* https://github.com/hashicorp/go-tfe/pull/64/files
* https://github.com/hashicorp/terraform-website/pull/724
