### ISSUE TITLE
[Feature Request] Add support for TFE provider to manage VCS provider connections and private modules for organizations

### ISSUE THREAD

**Issue by sahilarora535** [terraform-providers/terraform-provider-tfe#79]
Hi,
It would be great to have resources in TFE provider to manage private modules registry and VCS provider in a TFE organization using terraform configurations.

**Comment by iniinikoski** [comment]
This would be awesome...

**Comment by eboumendil** [comment]
It would be the best

**Comment by allisonis** [comment]
Hello +1 we would like this.

**Comment by iiro** [comment]
This would be very much needed yes...

**Comment by mkjmdski** [comment]
The popular usecase I am having for this Feature Request is that our gitlab EE instance sometimes resets VCS connection on its side and it requires:
1. manual update (for two terraform enterprise instances)
2. then updating oauth token ID in all workspaces by code (and we are perfectly fine with this step)
3. readding all moduels with new oauth token ID

seems like this feature request could codify step 1,3 what would ease our life with gitlab bugs... Thanks in advance for implementation, looking forward for it :)

**Comment by lafentres** [comment]
Hello! We just released [v0.20.0](https://github.com/terraform-providers/terraform-provider-tfe/blob/v0.20.0/CHANGELOG.md) this morning, which includes support for managing VCS-back registry modules.

You can manage VCS connection for all VCS providers except Bitbucket Server, Bitbucket Cloud, and Azure DevOps Services with the [tfe_oauth_client resource](https://www.terraform.io/docs/providers/tfe/r/oauth_client.html).
