### ISSUE TITLE
file-triggers-enabled and trigger-prefixes still not set (v0.10.1)

### ISSUE THREAD

**Issue by miklosbarabasForm3** [terraform-providers/terraform-provider-tfe#83]
Hey

After upgrading to use v0.10.1, we still see these always re-planned and not been set:
```
      file_triggers_enabled: "false" => "true"
      trigger_prefixes.#:    "0" => "1"
      trigger_prefixes.0:    "" => "tf"
```

https://github.com/terraform-providers/terraform-provider-tfe/pull/81

**Comment by svanharmelen** [comment]
Hi @miklosbarabasForm3, I cannot reproduce this (aka it works as expected when I try this) so I'm curious if you still have issues with this?

**Comment by caseylang** [comment]
Closing this ticket due to inactivity. If you continue to an issue, please let us know!
