### ISSUE TITLE
Dangling sentence in tfe_policy_set documentation

### ISSUE THREAD

**Issue by clebio** [terraform-providers/terraform-provider-tfe#84]
The line on the `tfe_policy_set` resource documentation [1] for `workspace_external_ids` trails off:

> workspace_external_ids - (Optional) A list of workspace external IDs. If

If ... what? -- _shakes monitor_. 
[1]: https://www.terraform.io/docs/providers/tfe/r/policy_set.html#workspace_external_ids

**Comment by chrisarcand** [comment]
Thanks ^_^

**Comment by mechastorm** [comment]
I am still seeing the same dangling sentence on the live site - https://www.terraform.io/docs/providers/tfe/r/policy_set.html#workspace_external_ids

Do the changes take a while to propogate?

**Comment by chrisarcand** [comment]
Yup, they do. The changes should take effect soon though.
