### ISSUE TITLE
Notification configuration creation fails with "Error creating notification configuration my-test-notification-configuration: resource not found"

### ISSUE THREAD

**Issue by iniinikoski** [terraform-providers/terraform-provider-tfe#89]
Using the example from here: https://www.terraform.io/docs/providers/tfe/r/notification_configuration.html (only disabling the ORG creation) - tf apply fails with this:

```
tfe_workspace.test: Creating...
tfe_workspace.test: Creation complete after 2s [id=XXXX/my-workspace-name]
tfe_notification_configuration.test: Creating...

Error: Error creating notification configuration my-test-notification-configuration: resource not found

  on main.tf line 18, in resource "tfe_notification_configuration" "test":
  18: resource "tfe_notification_configuration" "test" {
```

Terraform version: 0.12.7
TFE module version: 0.11.0

Should be very repeatable error...

I'm using a organization token.

**Comment by svanharmelen** [comment]
You have to use either a team token or (preferred) a personal token for this to work.

**Comment by iniinikoski** [comment]
Oh, interesting... I trusted the org token would be the correct one, as this is what they say in TFE UI as well:

```
The organization API token is used to manage teams, team membership and workspaces. This token does not have permission to perform plans and applies in workspaces.
```

So, sounds like we'd need to dedicate an internal system user for managing workspaces... Does not sound great...

**Comment by svanharmelen** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen it in case you have more related questions or feedback.

**Comment by dorg-thaskins** [comment]
The organization token is intended to manage workspaces - why would the workspace notifications be a separate use case?

**Comment by iniinikoski** [comment]
> The organization token is intended to manage workspaces - why would the workspace notifications be a separate use case?

Hi @dorg-thaskins and others. I've opened a support ticket to Hashicorp about this. I advice others to do the same. I wasn't at all pleased of closing the issue. Mur.
