### ISSUE TITLE
`Token` attribute for `tfe_organization_token` doesn't exist

### ISSUE THREAD

**Issue by philbal611** [terraform-providers/terraform-provider-tfe#90]
Per the [`tfe_organization_token` documentation](https://www.terraform.io/docs/providers/tfe/r/organization_token.html), the resource should maintain a `token` attribute refernce. Given the following configuration, the following error is received:

```hcl
resource "tfe_organization" "my_org" {
  name                    = "My-Org"
  email                   = "${var.tfe_admin_email}"
  session_timeout_minutes = "30"
}

resource "tfe_organization_token" "my_org_token" {
  organization = "${tfe_organization.my_org.name}"
}

output "my_org_token" {
  value       = "${tfe_organization_token.my_org_token.token}"
}
```

```
Error: Error running plan: 1 error occurred:
	* output.my_org_token: Resource 'tfe_organization_token.my_org_token' does not have attribute 'token' for variable 'tfe_organization_token.my_org_token.token'
```

**Note**: organization & organization token were imported in this context. State for the org token still shows no `token` attribute:

```json
"tfe_organization_token.my_org_token": {
    "type": "tfe_organization_token",
    "depends_on": [],
    "primary": {
    "id": "My-Org",
    "attributes": {
        "id": "My-Org",
        "organization": "My-Org"
    },
    "meta": {},
    "tainted": false
    },
    "deposed": [],
    "provider": "provider.tfe"
},
```

**Comment by svanharmelen** [comment]
@philbal611 you cannot import the token itself as it's only returned by the API (for security reasons) when you create it. So you can import the resource to indicate that you want to manage this token (and any recreates you might want to trigger in the future) using Terraform, but you cannot import the already created token value.

**Comment by svanharmelen** [comment]
Closing this one as there isn't much we can do to change this behavior. Feel free to reopen the issue if you additional questions or feedback.
